[project]
name = "lut-generation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.5",
    "pillow>=12.0.0",
    "torch>=2.9.1",
    "typer>=0.20.0",
]
